# Generated by Django 6.0.1 on 2026-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.BigIntegerField(unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('math', models.IntegerField(verbose_name='数学')),
                ('chinese', models.IntegerField(verbose_name='语文')),
                ('english', models.IntegerField(verbose_name='英语')),
                ('total', models.IntegerField(blank=True, default=0, verbose_name='总分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
                'ordering': ['student_id'],
            },
        ),
    ]
